language: csharp
solution: WebDAVMailRuCloud.sln
dotnet: 2.0.0
branches:
  only: 
#    - master
    - /^\d+\.\d+\.\d+\.\d+$/
install:
  - nuget restore WebDAVMailRuCloud.sln
script:
  - nuget restore
  - msbuild /t:"Restore;Build" /p:Configuration="Release" /p:Platform="Any CPU" WebDAVMailRuCloud.sln
  - dotnet publish /home/travis/build/yar229/WebDavMailRuCloud/WDMRC.Console/WDMRC.Console.csproj -c Release -f netcoreapp2.0

#before_script: 
#    - |
#      # ...
#      sed -ie 's/\[assembly: AssemblyFileVersion("1.0.0.0")\]/\[assembly: AssemblyFileVersion(" ${TRAVIS_TAG} ")\]/g' /home/travis/build/yar229/WebDavMailRuCloud/WDMRC.Console/Properties/AssemblyInfo.cs
#      # ...
#    - |
#      # ...
#      sed -ie 's/\[assembly: AssemblyVersion("1.0.0.0")\]/\[assembly: AssemblyVersion(" ${TRAVIS_TAG} ")\]/g' /home/travis/build/yar229/WebDavMailRuCloud/WDMRC.Console/Properties/AssemblyInfo.cs
#      # ...      
  #- "sed -ie 's/\\[assembly: AssemblyFileVersion(\"1.0.0.0\")\\]/\\[assembly: AssemblyFileVersion(\"$TRAVIS_TAG\")\\]/g' /home/travis/build/yar229/WebDavMailRuCloud/WDMRC.Console/Properties/AssemblyInfo.cs"
  #- "sed -ie 's/\\[assembly: AssemblyVersion(\"1.0.0.0\")\\]/\\[assembly: AssemblyVersion(\"$TRAVIS_TAG\")\\]/g' /home/travis/build/yar229/WebDavMailRuCloud/WDMRC.Console/Properties/AssemblyInfo.cs"
before_deploy: 
  - rm /home/travis/build/yar229/WebDavMailRuCloud/WDMRC.Console/bin/Release/net452/*.pdb
    && zip WebDAVCloudMailRu-$TRAVIS_TAG-dotNet45.zip /home/travis/build/yar229/WebDavMailRuCloud/WDMRC.Console/bin/Release/net452/*.* -j
    && rm /home/travis/build/yar229/WebDavMailRuCloud/WDMRC.Console/bin/Release/netcoreapp2.0/publish/*.pdb
    && zip WebDAVCloudMailRu-$TRAVIS_TAG-dotNetCore20.zip /home/travis/build/yar229/WebDavMailRuCloud/WDMRC.Console/bin/Release/netcoreapp2.0/publish/*.* -j
deploy:
  provider: releases
  api_key:
    secure: exmPJoDjRwHVSDW2TyKI97zpddGEbrVOv6apNgngbdOjWLIgtH+TVMsO69SrY9YIJHoQPlgoGCaDMIps38jvbayF1It7E48nEkMA24TkpTLNEJyUQnD5+U59hFOEvw8VOb8DPpLHY97rC8V5OckRIiEYEn76pWvGiqe4uH9fOeAJzjqSQHJaYW8fDAgSK5MOSRHX0tOfiJ5hRIESgDFu6VA20ffl1y1WbvHw3vBadUwVlUjHiu787snKLYmrPLtKPmeSasfOREM+IRel07Hz6OM80Imz0nmDjgJt3BSuGoO6+v6TAWD24+K4iG9VGSfJMxb5ApEbUIU8cLjAylJGlgBqu9WFHmmt0CAPnMHBFkQJvE7JTpnSfI+G2Q7wRzgTLpGQvoad7XpudoN6SOXZR2Dg45Htdb9cUlZnXOMpczNpuZlO8GWPj/wqwDwZ0PUR83FYZbTCke1XVdQlLibz8TvPaK3SFTmYC7qxcSEkeqryyDmP8kqdL+T5UmI0IWlkuBwO97rjWVK5DkAF3eqrHufggCwWUaogTdtOZcXErkosyxgwrFWBN18U630xjSmu3VqNFlCs3nqdtlI7S3LElY5F3cPDXFQr7jbHbX9y+YvfkU1WNGwpEGRZ66gJoz2a4dmbfFCi6TAhUWNetwHfeBkqP9lgZcvi88mMc/MJCyQ=
#  file: "wdmrc-mono-$TRAVIS_TAG.tar.gz"
  file:
    - "WebDAVCloudMailRu-$TRAVIS_TAG-dotNet45.zip"
    - "WebDAVCloudMailRu-$TRAVIS_TAG-dotNetCore20.zip"  
  skip_cleanup: true
  on:
    repo: yar229/WebDavMailRuCloud
    tags: true    
