# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  tags:
    include:
    - '1.*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: .NET Build
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/t:"Restore;Build" /p:Configuration="Release" /p:Platform="Any CPU"'

- task: ArchiveFiles@2
  displayName: .NET Build Archive
  inputs:
    rootFolderOrFile: 'WDMRC.Console/bin/Release/net461/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/WebDAVCloudMailRu-$(Build.SourceBranchName)-dotNet461.zip'
    replaceExistingArchive: true

- task: DotNetCoreCLI@2
  displayName: .NETCore Build
  inputs:
    command: 'publish' 
    projects: 'WDMRC.Console/WDMRC.Console.csproj'
    publishWebProjects: false # Required when command == Publish
    arguments: '--configuration $(BuildConfiguration) --framework netcoreapp2.2'

- task: ArchiveFiles@2
  displayName: .NETCore Build Archive
  inputs:
    rootFolderOrFile: 'WDMRC.Console/bin/Release/netcoreapp2.2/publish/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/WebDAVCloudMailRu-$(Build.SourceBranchName)-dotNetCore22.zip'
    replaceExistingArchive: true



#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'
